"""Fix FK constraint for equipment-to-student mapping

Revision ID: 0d9fe461e038
Revises: d485d5ef25e8
Create Date: 2025-07-25 22:44:10.474442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9fe461e038'
down_revision = 'd485d5ef25e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_roll', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key('fk_equipment_assigned_to_roll', 'workstation', ['assigned_to_roll'], ['roll'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_assigned_to_roll', type_='foreignkey')
        batch_op.drop_column('assigned_to_roll')

    # ### end Alembic commands ###
