"""Add assignment tracking fields

Revision ID: 137d7406ca9f
Revises: 0d9fe461e038
Create Date: 2025-07-25 23:27:16.903648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137d7406ca9f'
down_revision = '0d9fe461e038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_by', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('assigned_date')

    # ### end Alembic commands ###
