"""Add is_active to User

Revision ID: 757d369847ec
Revises: fe4324b4f8ca
Create Date: 2025-07-20 21:29:02.212251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757d369847ec'
down_revision = 'fe4324b4f8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
