"""Added invoice_number, cost_per_unit, warranty_expiry

Revision ID: d485d5ef25e8
Revises: 757d369847ec
Create Date: 2025-07-21 14:41:42.429814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd485d5ef25e8'
down_revision = '757d369847ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('warranty_expiry', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('warranty_expiry')
        batch_op.drop_column('cost_per_unit')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
